# Generated by Django 2.1.7 on 2020-12-27 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=20, verbose_name='部门名称')),
                ('department_detail', models.CharField(default='', max_length=100, verbose_name='部门介绍')),
                ('revise_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='revise date')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='', max_length=20, verbose_name='员工姓名')),
                ('job_number', models.CharField(default='', max_length=20, verbose_name='工号')),
                ('mac_address', models.CharField(default='', max_length=20, verbose_name='mac地址')),
                ('revise_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='revise date')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='ip_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_number', models.CharField(default='', max_length=20, verbose_name='ip地址')),
                ('ip_state', models.SmallIntegerField(choices=[(0, '已分配'), (1, '未分配')], default=1, verbose_name='ip使用状态')),
                ('revise_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='revise date')),
                ('ip_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': 'ip地址池信息',
                'verbose_name_plural': 'ip地址池信息',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(default='', max_length=20, verbose_name='所属厂家')),
                ('switch_number', models.CharField(default='', max_length=20, verbose_name='交换机编号')),
                ('seat_number', models.IntegerField(default=0, verbose_name='座位号')),
                ('state', models.CharField(default='', max_length=20, verbose_name='状态信息')),
                ('revise_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='revise date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '交换机信息',
                'verbose_name_plural': '交换机信息',
                'db_table': 'switch',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.ip_state', verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='information',
            name='port_switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.switch', verbose_name='所用交换机'),
        ),
    ]
