# Generated by Django 2.1.7 on 2020-12-28 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterField(
            model_name='department',
            name='revise_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='revise_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='ip_state',
            name='ip_state',
            field=models.SmallIntegerField(choices=[(0, '已分配'), (1, '未分配')], default=1, verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='ip_state',
            name='revise_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='revise_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '已分配'), (1, '未分配')], default=1, verbose_name='使用状态'),
        ),
    ]
