# Generated by Django 2.1.7 on 2021-01-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netmanage', '0002_auto_20201228_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='state',
        ),
        migrations.AddField(
            model_name='information',
            name='seat_number',
            field=models.CharField(default='', max_length=20, verbose_name='座位号'),
        ),
        migrations.AddField(
            model_name='switch',
            name='account_switch',
            field=models.CharField(default='', max_length=20, verbose_name='交换机账号'),
        ),
        migrations.AddField(
            model_name='switch',
            name='password_switch',
            field=models.CharField(default='', max_length=20, verbose_name='交换机密码'),
        ),
        migrations.AddField(
            model_name='switch',
            name='state_ip',
            field=models.CharField(default='', max_length=20, verbose_name='所绑定的ip'),
        ),
        migrations.AddField(
            model_name='switch',
            name='state_mac',
            field=models.CharField(default='', max_length=20, verbose_name='所绑定的mac'),
        ),
        migrations.AddField(
            model_name='switch',
            name='type_switch',
            field=models.SmallIntegerField(choices=[(0, 'access'), (1, 'trunk'), (2, 'hybrid')], default=1, verbose_name='交换机链路类型'),
        ),
        migrations.AlterField(
            model_name='information',
            name='port_switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmanage.switch', verbose_name='所用交换机端口'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_number',
            field=models.CharField(default='', max_length=20, verbose_name='交换机设备号-端口号'),
        ),
    ]
